### ISSUE TITLE
pk.dat of sgc_z3 is missing

### ISSUE THREAD

**Issue by JiachuanXu** [Michalychforever/lss_montepython#2]
Hi all, 
    I'm a second year grad in the University of Arizona. I'm working with Dr. Tim Eifler, currently we are trying to incorporating this great EFT analysis on BOSS DR12 into our DES analysis as a prior, and I have some difficulties in reproducing the posterior in your _[Cosmological Parameters from the BOSS Galaxy Power Spectrum](https://arxiv.org/abs/1909.05277)_ paper.
    It seems the data vector pk.dat of sgc_z3 is missing. Could you please add the data vector to the repository? I really appreciate that! Thanks! 

Best,
Jiachuan

**Comment by Michalychforever** [comment]
Hi Jiachuan,
Thanks for pointing this out! I've uploaded the missing pk.dat file now. Let me know if you need any assistance with the code.
