### ISSUE TITLE
Exactly which spectra are being computed in these likelihoods 

### ISSUE THREAD

**Issue by alexander-reeves** [Michalychforever/lss_montepython#3]
Dear all, 

could you describe to me exactly which specta are being computed in these likelihood functions: is this the total real space matter spectrum (as would be evaluated using the convenient function "M.pk_mm_real(cs)" in CLASS-PT). Also, is IR resummation being included? Sorry if this is a very basic question but I can't tell for the code written in the likelihoods what is being calculated.

**Comment by Michalychforever** [comment]
Hi Alex,

CLASS-PT computes many different spectra: matter-matter, galaxy-matter, galaxy-galaxy + matter and galaxy power spectrum multipoles in redshift space. In our BOSS likelihood we use the redshift-space multipoles. IR resummation is always included in the likelihoods. If you want to check its effect, you can play with the option 'IR resummation':'Yes' in classy.

As far as the real space spectrum of matter is concerned, you can build a likelihood with the following call: 

cosmo.set(....)  --- this is the usual classy call, make sure you use 'non linear':'PT'
z =0 
k=np.linspace(0.001,0.2,100)
krange=len(k)
all_theory = cosmo.get_pk_mult(k*h,z,orange)

cs = 1 (this is the dark matter effective sound speed, set to 1 for simplicity here)

Pmm = (all_theory[14]+all_theory[0] + 2. * cs * all_theory[10]/h ** 2.)* h ** 3

**Comment by alexander-reeves** [comment]
Thank you- that clears up what I was unsure about!
