### ISSUE TITLE
Where can I find the highz and lowz redshift space multipole data? 

### ISSUE THREAD

**Issue by alexander-reeves** [Michalychforever/lss_montepython#4]
Dear all, 

I am trying to reconstruct the 'multipole comparison plot' of Ivanov et al(2020) [figures 3 and 4]. I have managed to download and calculate the redshift-space multiples of the BOSS data found here https://data.sdss.org/sas/dr12/boss/lss/ but this doesn't seem to be the same data used in the plot (this data is split into CMASS and LOWZ samples rather than the 3 redshift bins (z1=0.38, z3=0.61) mentioned in the paper- I could be wrong but it seems that these are different datasets?). Is there somewhere I can download either the raw redshift-space galaxy power spectrum data or the constructed multipole and errorbar data used in the plot?

**Comment by Michalychforever** [comment]
Hi Alex,

You can find the spectra and covariance matrices in folders data/ngc_z3,  data/sgc_z3,  data/ngc_z1, data/sgc_z1. These are four independent BOSS data chunks. The files pk.dat contain spectra, and covmat.dat - errorbars. To reproduce Figs. 3 and 4 you need diagonal parts of these covariance matrices. These spectra were computed directly from the BOSS raw data taken from https://data.sdss.org/sas/dr12/boss/lss/. The files *_CMASSLOWZTOT_North/South contain all the data from release 12. I sliced this data just like in the latest BOSS paper, using the z1 (0.2<z<0.5) and z3 (0.5< z < 0.75) redshift bins

**Comment by alexander-reeves** [comment]
Thank you! That's exactly what I was looking for.
